sudo: required

services:
  - docker

before_install:
  # Install Docker Compose.
  - curl -L https://github.com/docker/compose/releases/download/VERSION_NUM/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
  - chmod +x /usr/local/docker-compose

  # Create an .env file from the example.
  - cp .env.example .env

script:
  - docker-compose build
  - docker-compose up -d
